# Generated by Django 3.1 on 2020-10-02 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='added_date',
        ),
    ]
